site_name: studies
repo_url: https://github.com/jbcodeforce/spark-studies
nav:
  - Introduction: index.md
  - Develop on Spark: dev-on-spark.md
  - Scala summary: scala_summary.md
  - Cloud object storage: cloud-storage.md
  - Compendium: compendium.md
 

theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences