site_name: Spark studies
repo_url: https://github.com/jbcodeforce/spark-studies
nav:
  - Introduction: index.md
  - Develop with Spark:
    - Getting Started: dev/index.md
    - Deployments: dev/deployment.md
    - PySpark: dev/python.md
    - Streaming: dev/streaming.md
    - Examples: dev/examples.md
  - Scala summary: scala_summary.md
  - Databricks: https://jbcodeforce.github.io/techno/databricks/
  - Compendium: compendium.md
  - Return to main: https://jbcodeforce.github.io

theme: 
  name: material
  logo: images/apache_spark_logo.png
extra_css: ["extra.css"]
features:
    - content.code.annotate
    - content.tooltips
    # - navigation.tabs
    - navigation.instant
    #- navigation.tracking
    # - navigation.sections
    # - navigation.expand
    - navigation.tabs.sticky
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details